### ISSUE TITLE
Allow mocking and subclassing of PHPProphet

### ISSUE THREAD

**Issue by cyruscollier** [php-mock/php-mock-prophecy#3]
Having the `final` declaration on the `PHPProphet` class means you cannot mock it in tests or extend the functionality. I suggest removing the `final` declaration and making the `$prophet` property protected.

[Pull Request #2](https://github.com/php-mock/php-mock-prophecy/pull/2)

**Comment by malkusch** [comment]
The hole point of declaring the class final and setting the property private is, I didn't design the class for extension. Your use case is very unique, as normal clients would not have to mock that class. Couldn't you design your test to use the actual implementation?

If you really need a mock, you could refactor your code to not use PHPProphet directly, but through a proxy. Then you have full control over the design of that proxy.

Please point me to your test, so that I can have a look on my own of the situation.

**Comment by cyruscollier** [comment]
I wasn't planning on subclassing PHPProphet, but needing to mock PHPProphet as a dependency in another library hardly seems like a unique use case. In my opinion, the only classes that could be `final` are those that have no dependencies or side effects of their own and do not need to be mocked, like domain entities or value objects, for example.

**Comment by malkusch** [comment]
>  needing to mock PHPProphet as a dependency in another library hardly seems like a unique use case

Mocking a mocking library is a unique use case.

> In my opinion, the only classes that could be `final` are those that have no dependencies or side effects of their own

Thank you for sharing your opinion on the `final` construct. I follow [Josh Bloch's approach](http://checkstyle.sourceforge.net/config_design.html#DesignForExtension) and protect the clients to mess around with sub classing.

But I see, you don't want to mess around, you just need a mock. As you pointed already out your familiarity with domain driven design, then I suggest using an anti corruption layer which you can mock:

```
interface MockablePHPProphet {
    public function prophesize($namespace);
}

final class PHPProphetProxy implements MockablePHPProphet {
    private $phpProphet;
    public function prophesize($namespace)
    {
        return $this->phpProphet->prophesize($namespace);
    }
}
```

**Comment by cyruscollier** [comment]
I was actually considering doing something similar to what you suggest. However, I think I'm satisfied for now about the test coverage of my classes, given the early stage of the project. If things grow in complexity, I'll probably need a mockable interface for both PHPProphet and the special collaborator class for phpspec, since that has been difficult to mock as well (a collaborator of a collaborator!). Thanks.
